apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-{{ .Values.config.POSTGRES_DB }}
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-{{ .Values.config.POSTGRES_DB }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: postgres-{{ .Values.config.POSTGRES_DB }}
  template:
    metadata:
      labels:
        app: postgres-{{ .Values.config.POSTGRES_DB }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.config.POSTGRES_DB }}"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret-{{ .Values.config.POSTGRES_DB }}
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-{{ .Values.config.POSTGRES_DB }}
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-{{ .Values.config.POSTGRES_DB }}-pvc
