apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-{{ .Values.config.POSTGRES_DB }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
