apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ .Values.config.POSTGRES_DB }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | b64enc }}
