apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: {{ .Values.namespace }}
data:
  DJANGO_SETTINGS_MODULE: "{{ .Values.env.DJANGO_SETTINGS_MODULE }}"
  DEBUG: "{{ .Values.env.DEBUG }}"
  DJANGO_ALLOWED_HOSTS: "{{ .Values.env.DJANGO_ALLOWED_HOSTS }}"
  SILVER_DB_HOST: "{{ .Values.db.silver.host }}"
  SILVER_DB_PORT: "{{ .Values.db.silver.port }}"
  GOLD_DB_HOST: "{{ .Values.db.gold.host }}"
  GOLD_DB_PORT: "{{ .Values.db.gold.port }}"
