apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: {{ .Values.namespace }}
data:
  debug: "{{ .Values.env.DEBUG }}"
  django_allowed_hosts: "{{ .Values.env.DJANGO_ALLOWED_HOSTS }}"
  silver_db_host: "{{ .Values.db.silver.host }}"
  silver_db_port: "{{ .Values.db.silver.port }}"
  silver_db_name: "{{ .Values.db.silver.name }}"
  silver_sql_engine: "{{ .Values.db.silver.engine }}"
  gold_db_host: "{{ .Values.db.gold.host }}"
  gold_db_port: "{{ .Values.db.gold.port }}"
  gold_db_name: "{{ .Values.db.gold.name }}"
  gold_sql_engine: "{{ .Values.db.gold.engine }}"
