apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | b64enc }}
  SILVER_DB_USER: {{ .Values.secret.SILVER.DB_USER | b64enc }}
  SILVER_DB_PASSWORD: {{ .Values.secret.SILVER.DB_PASSWORD | b64enc }}
  GOLD_DB_USER: {{ .Values.secret.GOLD.DB_USER | b64enc }}
  GOLD_DB_PASSWORD: {{ .Values.secret.GOLD.DB_PASSWORD | b64enc }}
