namespace: dataforge-test

replicas: 1

image:
  repository: postgres
  tag: 14.5

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

persistence:
  enabled: true
  size: 10Gi

config:
  POSTGRES_DB: golddb

secret:
  POSTGRES_USER: "golduser"  # Specifico per Gold
  POSTGRES_PASSWORD: "goldsafe"
