replicas: 1

namespace: dataforge-test

image:
  repository: django-dev
  tag: latest

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

env:
  DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"

persistence:
  media:
    enabled: true
    size: 5Gi
    name: django-media-pvc
    storageClassName: "microk8s-hostpath"
    accessModes:
      - ReadWriteOnce
  static:
    enabled: true
    size: 5Gi
    name: django-static-pvc
    storageClassName: "microk8s-hostpath"
    accessModes:
      - ReadWriteOnce

secret:
  SECRET_KEY: "super-secret-key"
  SILVER_DB_USER: "silveruser"
  SILVER_DB_PASSWORD: "silversafe"
  GOLD_DB_USER: "golduser"
  GOLD_DB_PASSWORD: "goldsafe"

db:
  silver:
    host: "postgres-silver"
    port: "5432"
    name: "silverdb"
    engine: "django.db.backends.postgresql"
  gold:
    host: "postgres-gold"
    port: "5432"
    name: "golddb"
    engine: "django.db.backends.postgresql"

